In [3]:
import tensorflow as tf


In [ ]:
# intialization of tensorflow
# tensor are multi -dimensional array with data type dtype

In [6]:
x =  tf.constant(20)
print(x)


tf.Tensor(20, shape=(), dtype=int32)


In [8]:
y = tf.constant([[1, 2, 3] , [4, 5, 6]])
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [9]:
x  = tf.ones([3, 3])
# it will create the no of elements one 
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
#zeros method will create the matrix of zeros
x = tf.zeros([2, 3])
x


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [14]:
# for indentity  matrix we have eye method.

x = tf.eye(3)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [15]:
# similar to numpy we have  a range function in tensors

x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [17]:
y = tf.range(start = 1 , limit = 10 , delta = 2)
y

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [ ]:
# Mathematical operation , we can mathematical operation like addition subraction and matrix multiplication

In [23]:
a = tf.constant([[1, 2, 3] , [4, 5, 6]])
b = tf.constant([[7, 8, 9] , [10 , 11, 12]])

print(tf.add(a , b))
print(tf.subtract(a ,b))

print(tf.divide(a, b))

print(tf.multiply(a ,b))

tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-6 -6 -6]
 [-6 -6 -6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32)


In [ ]:
# indexing in tensors

In [26]:
x = tf.range(9)
print(x[:, ])
print([x[:, ]])
print(x[::2])

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
[<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>]
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [30]:
# Re shape
x = tf.range(9)
x

tf.reshape(x, (3 ,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

tensor([0.8889, 0.4207, 0.5841])

AttributeError: module 'torch.cuda' has no attribute 'is_aavailable'