In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow 
from tensorflow import keras
from tensorflow.keras.layers import Dense
import keras
from keras.models import Sequential
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_moons

In [4]:
X,y = make_moons(n_samples = 250 , noise = 0.05 , random_state = 20)

In [11]:
X.shape

(250, 2)

In [10]:
y.shape


(250,)

In [12]:
plt.scatter(X[: ,0] , X[: ,1] , c =y , s =100)
plt.show()

In [14]:
# model building
model = Sequential()
model.add(Dense(10 , activation = 'sigmoid' , input_dim  =2))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(10 , activation = 'sigmoid'))
model.add(Dense(1, activation = 'sigmoid'))

In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 10)             │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,141 (4.46 KB)

 Trainable params: 1,141 (4.46 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile(loss = 'binary_crossentropy', optimizer = "Adam" , metrics = ['accuracy'])

In [28]:
# weights of layers
model.get_weights()[0]

old_weights = model.get_weights()[0]
old_weights

array([[-0.3430264 ,  0.22065851,  0.09636422,  0.05972364,  0.00328829,
         0.6993962 ,  0.49242082, -0.60724384,  0.06437802,  0.0173734 ],
       [ 0.60923046,  0.51098585, -0.49352404,  0.36853975,  0.56951565,
         0.28278404, -0.39260504,  0.5132846 ,  0.28030345, -0.6616491 ]],
      dtype=float32)

In [20]:
X_train , X_test , y_train , y_test = train_test_split(X,y ,test_size = 0.2 , random_state = 20)

In [36]:
model.fit(X_train , y_train , epochs = 1)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8698 - loss: 0.3470 


In [26]:
new_weights =  model.get_weights()[0]
new_weights

array([[-0.3430264 ,  0.22065851,  0.09636422,  0.05972364,  0.00328829,
         0.6993962 ,  0.49242082, -0.60724384,  0.06437802,  0.0173734 ],
       [ 0.60923046,  0.51098585, -0.49352404,  0.36853975,  0.56951565,
         0.28278404, -0.39260504,  0.5132846 ,  0.28030345, -0.6616491 ]],
      dtype=float32)

In [32]:
# now we can calculate gradient = gradient = (old_weight-new_weights)/0.01

gradient = (old_weights - new_weights) / 0.01
gradient

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
# we can clearly see that our gradient is converging to zero and the change in old weight and new wieght after training in 
# negligible

# so there is vanishing gradient problem


In [ ]:
# more epochs

In [38]:
model.fit(X_train , y_train , epochs = 100)

Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8777 - loss: 0.3296 
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8784 - loss: 0.3419 
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3636 
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8636 - loss: 0.3471 
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8556 - loss: 0.3706 
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8936 - loss: 0.3317 
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8814 - loss: 0.3247 
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8709 - loss: 0.3345 
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8595 - loss: 0.3591 
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8570 - loss: 0.3568 
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8508 - loss: 0.3685 
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8723 - los

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8455 - loss: 0.3927 
Epoch 70/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8722 - loss: 0.3228 
Epoch 71/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8677 - loss: 0.3575 
Epoch 72/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8670 - loss: 0.3339 
Epoch 73/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8616 - loss: 0.3546 
Epoch 74/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8795 - loss: 0.3278 
Epoch 75/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8653 - loss: 0.3543 
Epoch 76/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8885 - loss: 0.3277 
Epoch 77/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8474 - loss: 0.3867 
Epoch 78/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8642 - loss: 0.3652 
Epoch 79/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8539 - loss: 0.3590 
Epoch 80/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8516 - loss: 0